##############################################################################
#Recode latin taxa names
#Jaelyn Bos
##############################################################################

#This (very long) function is called by both the "Create OS community data.R"
#and "Create GC community data.R" scripts. It replaces latin names with 
#USFS species codes, and incorrect species codes with correct ones

##############################################################################
#Required packages: stringr
##############################################################################

library(stringr)

usfs.codes<-function(TaxaNames){
x<-as.character(TaxaNames)
x<-str_replace(x,"Trifolium repens","TRRE3")
x<-str_replace(x,"Zelkova serrata","ZESE80")
x<-str_replace(x,"Vitis riparia","VIRI")
x<-str_replace(x,"Vinca minor","VIMI2")
x<-str_replace(x,"Viburnum lentago","VILE")
x<-str_replace(x,"Viburnum lentago","VILE")
x<-str_replace(x,"Viburnum dentatum","VIDE")
x<-str_replace(x,"Viburnum acerifolium","VIAC")
x<-str_replace(x,"Verbena officinalis","VEOF")
x<-str_replace(x,"Ulmus americana","ULAM")
x<-str_replace(x,"Toxicodendron radicans","TORA2")
x<-str_replace(x,"Taraxacum","TARAX")
x<-str_replace(x,"Smilax rotundifolia","SMRO")
x<-str_replace(x,"Smilax rotundifolia","SMRO")
x<-str_replace(x,"Sassafras albidum","SAAL5")
x<-str_replace(x,"Rumex acetosa","RUAC2")
x<-str_replace(x,"Rubus trainthus","RUAC2")
x<-str_replace(x,"Rosa Multiflora","ROMU")
x<-str_replace(x,"Rosa multiflora","ROMU")
x<-str_replace(x,"Robinia pseudoacacia","ROPS")
x<-str_replace(x,"Rubus occidentalis","RUOC")
x<-str_replace(x,"Prunus avium","PRAV")
x<-str_replace(x,"Polyganum perfoliatum","POPE10")
x<-str_replace(x,"Polygonum perfoliatum","POPE10")
x<-str_replace(x,"Polygonum perfoliata","POPE10")
x<-str_replace(x,"Polygonum perfoliata","POPE10")
x<-str_replace(x,"Polyganum perfoliata","POPE10")
x<-str_replace(x,"Polyganum longisetum","POCEL")
x<-str_replace(x,"Polyganum longistem","POCEL")
x<-str_replace(x,"Polygonum longisetum","POCEL")
x<-str_replace(x,"Polygonum longistem","POCEL")
x<-str_replace(x,"Polyganum aviculare","POAV")
x<-str_replace(x,"Polygonum aviculare","POAV")
x<-str_replace(x,"Plantago asiatica","PLMA2")
x<-str_replace(x,"Pinellia ternata","PITE")
x<-str_replace(x,"Phytolacca americana","PHAM4")
x<-str_replace(x,"Perilla frutescens","PEFR4")
x<-str_replace(x,"Pathenocissus quinquefolia","PAQU2")
x<-str_replace(x,"Parthenocissus quinquefolia","PAQU2")
x<-str_replace(x,"Oxalis stricta","OXST")
x<-str_replace(x,"Osmundastrum cinnamomeum","OSCI")
x<-str_replace(x,"Osmunda japonica","")
x<-str_replace(x,"Morus rubra","MORU")
x<-str_replace(x,"Microstegium vimineum","MIVI")
x<-str_replace(x,"Microstegeum vimineum","MIVI")
x<-str_replace(x,"Malus spp","MALUS")
x<-str_replace(x,"Lycium chinense","LYCH")
x<-str_replace(x,"Lophatherum gracile","LOGR7")
x<-str_replace(x,"Lonicera japonica","LOJA")
x<-str_replace(x,"Liriodendron tulipifera","LITU")
x<-str_replace(x,"Lindera benzoin","LIBE3")
x<-str_replace(x,"Ipomoea hederacea","IPHE")
x<-str_replace(x,"Humula japonicus","HUJA")
x<-str_replace(x,"Helianthus tuberosus","HETU")
x<-str_replace(x,"Helianthus tuberosis","HETU")
x<-str_replace(x,"Hedera Helix","HEHE")
x<-str_replace(x,"Hedera helix","HEHE")
x<-str_replace(x,"Gymnema sylvestre","GYSY")
x<-str_replace(x,"Gleditsia triacanthos","GLTR")
x<-str_replace(x,"Glechoma hederacea","GLHE2")
x<-str_replace(x,"Geum canadense","GECA7")
x<-str_replace(x,"Geum aleppicum","GEAL7")
x<-str_replace(x,"Galium spurium","GAAP2")
x<-str_replace(x,"Galium concinnum","GACO3")
x<-str_replace(x,"Fraxinus pennsylvanica","FRPE")
x<-str_replace(x,"Fraxinus americana","FRAM2")
x<-str_replace(x,"Fragaria vesca","FRVE")
x<-str_replace(x,"Fallopia japonica","POCU6")
x<-str_replace(x,"Fagus grandifolia","FAGR")
x<-str_replace(x,"Fagaria vesca","FRVE")
x<-str_replace(x,"Fragaria vesca","FRVE")
x<-str_replace(x,"Euonymus alata","EUAL")
x<-str_replace(x,"Duchesnea indica","DUIN2")
x<-str_replace(x,"Dioscorea polystachya","DIOPOL")
x<-str_replace(x,"Digitaria sanguinalis","DISA")
x<-str_replace(x,"Cotinus coggygria","COCO10")
x<-str_replace(x,"Cornus florida","COFL2")
x<-str_replace(x,"Convallaria majalis","COMA7")
x<-str_replace(x,"Circaea alpina","CIAL")
x<-str_replace(x,"Cicaea alpina","CIAL")
x<-str_replace(x,"Centella asiatica","CEAS")
x<-str_replace(x,"Celastrus orbiculatus","CEOR7")
x<-str_replace(x,"Celustrus orbiculatus","CEOR7")
x<-str_replace(x,"Carya cordiformis","CACO15")
x<-str_replace(x,"Campsis radicans","CARA2")
x<-str_replace(x,"Buddleja lindleyana","BULI")
x<-str_replace(x,"Bidens bipinnata","BIBI7")
x<-str_replace(x,"Bidens pilosa","BIPI")
x<-str_replace(x,"Betula playphylla","BEPL2")
x<-str_replace(x,"Arthraxon hispidus","ARHI3")
x<-str_replace(x,"Arctium lappa","ARLA3")
x<-str_replace(x,"Amphicarpaea bracteata","AMBR2")
x<-str_replace(x,"Ampelosis glandulosa","AMBR7")
x<-str_replace(x,"Ampelopsis grandulosa","AMBR7")
x<-str_replace(x,"Ampelopsis glanulosa","AMBR7")
x<-str_replace(x,"Ampelopsis glandulosa","AMBR7")
x<-str_replace(x,"Amelanchier arborea","AMAR3")
x<-str_replace(x,"Alliaria petiolata","ALPE4")
x<-str_replace(x,"Allaria petiolata","ALPE4")
x<-str_replace(x,"Akebia quintata","AKQU")
x<-str_replace(x,"Ailanthus altissima","AIAL")
x<-str_replace(x,"Ageratina altissima","AGAL5")
x<-str_replace(x,"Acer rubrum","ACRU")
x<-str_replace(x,"Acer rubrum","ACRU")
x<-str_replace(x,"Circaea cordata","CIRCAEA")
x<-str_replace(x,"Circaea cordata","CIRCAEA")
x<-str_replace(x,"Diffusa diffusa","CODID3")
x<-str_replace(x,"Euonymus alata","EUAL13")
x<-str_replace(x,"Rubus occidentalis","RUBUS")
x<-str_replace(x,"Rubus trianthus","RUBUS")
x<-str_replace(x,"Viola collina","VIOLA")
x<-str_replace(x,"Smilax riparia","SMTA2")
x<-str_replace(x,"ALLIP","ALPE4")
x<-str_replace(x,"ACNE","ACNE2")
x<-str_replace(x,"ACNE22","ACNE2")
x<-str_replace(x,"CAGL","CAGL8")
x<-str_replace(x,"CAGL88","CAGL8")
x<-str_replace(x,"FRAM","FRAM2")
x<-str_replace(x,"FRAM22","FRAM2")
x<-str_replace(x,"CATO","CATO6")
x<-str_replace(x,"CATO66","CATO6")
x<-str_replace(x,"PRSE","PRSE2")
x<-str_replace(x,"PRSE22","PRSE2")
x<-str_replace(x,"PRSE23","PRSE2")
x<-str_replace(x,"CACO","CACO15")
x<-str_replace(x,"CACO1515","CACO15")
x<-str_replace(x,"ALPE42","ALPE4")
x<-str_replace(x,"HRHE","HEHE")
x<-str_replace(x,"QUPA","QUPA2")
x<-str_replace(x,"QUPA22","QUPA")
x<-str_replace(x,"CECA","CECA4")
x<-str_replace(x,"CECA44","CECA4")
x<-str_replace(x,"COFL","COFL2")
x<-str_replace(x,"COFL22","COFL2")
x<-str_replace(x,"MORU","MORU2")
x<-str_replace(x,"MORU22","MORU2")
x<-str_replace(x,"PATO","PATO2")
x<-str_replace(x,"PATO22","PATO2")
x<-str_replace(x,"PODE","PODE3")
x<-str_replace(x,"PODE33","PODE3")
x<-str_replace(x,"QUCO","QUCO2")
x<-str_replace(x,"QUCO22","QUCO2")
x<-str_replace(x,"QURA","QURU")
x<-str_replace(x,"TADI","TADI2")
x<-str_replace(x,"TADI22","TADI2")
x<-str_replace(x,"QUPR","QUPR2")
x<-str_replace(x,"QUPR22","QUPR2")
x<-str_replace(x,"QUPR2","QUMO4")
x<-str_replace(x,"QUMA","QUST")
x<-str_replace(x,"QUMA","QUST")
x<-str_replace(x,"QUAl","QUAL")
x<-str_replace(x,"QUPA","QUPA2")
x<-str_replace(x,"QUPA22","QUPA2")
x<-str_replace(x,"PYCA","PYCA80")
x<-str_replace(x,"PYCA8080","PYCA80")

return(x)
}
